on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Native - checkstyle, build, test
        shell: bash
        run: |
          nix develop --command bash -c "make clean dependencies checkstyle build-all test-coverage"

      - name: Native - security scan
        shell: bash
        run: |
          nix develop --command bash -c "make scan"

      - name: Native - archive scan results
        uses: actions/upload-artifact@v3
        with:
          name: grype.txt
          path: bin/grype.txt

      - name: OCI - prepare
        uses: docker/setup-buildx-action@v3

      - name: OCI - build
        shell: bash
        run: |
          docker buildx build --no-cache -t git.myservermanager.com/varakh/yafe:${{ forgejo.sha }} -f Dockerfile .
