// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package engine

import (
	"fmt"
	"strings"
)

const (
	// OutputTypeVariable is a OutputType of type variable.
	OutputTypeVariable OutputType = "variable"
	// OutputTypeFile is a OutputType of type file.
	OutputTypeFile OutputType = "file"
)

var ErrInvalidOutputType = fmt.Errorf("not a valid OutputType, try [%s]", strings.Join(_OutputTypeNames, ", "))

var _OutputTypeNames = []string{
	string(OutputTypeVariable),
	string(OutputTypeFile),
}

// OutputTypeNames returns a list of possible string values of OutputType.
func OutputTypeNames() []string {
	tmp := make([]string, len(_OutputTypeNames))
	copy(tmp, _OutputTypeNames)
	return tmp
}

// OutputTypeValues returns a list of the values for OutputType
func OutputTypeValues() []OutputType {
	return []OutputType{
		OutputTypeVariable,
		OutputTypeFile,
	}
}

// String implements the Stringer interface.
func (x OutputType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OutputType) IsValid() bool {
	_, err := ParseOutputType(string(x))
	return err == nil
}

var _OutputTypeValue = map[string]OutputType{
	"variable": OutputTypeVariable,
	"file":     OutputTypeFile,
}

// ParseOutputType attempts to convert a string to a OutputType.
func ParseOutputType(name string) (OutputType, error) {
	if x, ok := _OutputTypeValue[name]; ok {
		return x, nil
	}
	return OutputType(""), fmt.Errorf("%s is %w", name, ErrInvalidOutputType)
}

// MustParseOutputType converts a string to a OutputType, and panics if is not valid.
func MustParseOutputType(name string) OutputType {
	val, err := ParseOutputType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x OutputType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OutputType) UnmarshalText(text []byte) error {
	tmp, err := ParseOutputType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OutputType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// RunsOnKindHost is a RunsOnKind of type host.
	RunsOnKindHost RunsOnKind = "host"
)

var ErrInvalidRunsOnKind = fmt.Errorf("not a valid RunsOnKind, try [%s]", strings.Join(_RunsOnKindNames, ", "))

var _RunsOnKindNames = []string{
	string(RunsOnKindHost),
}

// RunsOnKindNames returns a list of possible string values of RunsOnKind.
func RunsOnKindNames() []string {
	tmp := make([]string, len(_RunsOnKindNames))
	copy(tmp, _RunsOnKindNames)
	return tmp
}

// RunsOnKindValues returns a list of the values for RunsOnKind
func RunsOnKindValues() []RunsOnKind {
	return []RunsOnKind{
		RunsOnKindHost,
	}
}

// String implements the Stringer interface.
func (x RunsOnKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RunsOnKind) IsValid() bool {
	_, err := ParseRunsOnKind(string(x))
	return err == nil
}

var _RunsOnKindValue = map[string]RunsOnKind{
	"host": RunsOnKindHost,
}

// ParseRunsOnKind attempts to convert a string to a RunsOnKind.
func ParseRunsOnKind(name string) (RunsOnKind, error) {
	if x, ok := _RunsOnKindValue[name]; ok {
		return x, nil
	}
	return RunsOnKind(""), fmt.Errorf("%s is %w", name, ErrInvalidRunsOnKind)
}

// MustParseRunsOnKind converts a string to a RunsOnKind, and panics if is not valid.
func MustParseRunsOnKind(name string) RunsOnKind {
	val, err := ParseRunsOnKind(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x RunsOnKind) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RunsOnKind) UnmarshalText(text []byte) error {
	tmp, err := ParseRunsOnKind(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *RunsOnKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// StepKindShell is a StepKind of type shell.
	StepKindShell StepKind = "shell"
)

var ErrInvalidStepKind = fmt.Errorf("not a valid StepKind, try [%s]", strings.Join(_StepKindNames, ", "))

var _StepKindNames = []string{
	string(StepKindShell),
}

// StepKindNames returns a list of possible string values of StepKind.
func StepKindNames() []string {
	tmp := make([]string, len(_StepKindNames))
	copy(tmp, _StepKindNames)
	return tmp
}

// StepKindValues returns a list of the values for StepKind
func StepKindValues() []StepKind {
	return []StepKind{
		StepKindShell,
	}
}

// String implements the Stringer interface.
func (x StepKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StepKind) IsValid() bool {
	_, err := ParseStepKind(string(x))
	return err == nil
}

var _StepKindValue = map[string]StepKind{
	"shell": StepKindShell,
}

// ParseStepKind attempts to convert a string to a StepKind.
func ParseStepKind(name string) (StepKind, error) {
	if x, ok := _StepKindValue[name]; ok {
		return x, nil
	}
	return StepKind(""), fmt.Errorf("%s is %w", name, ErrInvalidStepKind)
}

// MustParseStepKind converts a string to a StepKind, and panics if is not valid.
func MustParseStepKind(name string) StepKind {
	val, err := ParseStepKind(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x StepKind) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *StepKind) UnmarshalText(text []byte) error {
	tmp, err := ParseStepKind(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *StepKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
