// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package engine

import (
	"fmt"
	"strings"
)

const (
	// ConfigLogEncodingJson is a ConfigLogEncoding of type json.
	ConfigLogEncodingJson ConfigLogEncoding = "json"
	// ConfigLogEncodingConsole is a ConfigLogEncoding of type console.
	ConfigLogEncodingConsole ConfigLogEncoding = "console"
)

var ErrInvalidConfigLogEncoding = fmt.Errorf("not a valid ConfigLogEncoding, try [%s]", strings.Join(_ConfigLogEncodingNames, ", "))

var _ConfigLogEncodingNames = []string{
	string(ConfigLogEncodingJson),
	string(ConfigLogEncodingConsole),
}

// ConfigLogEncodingNames returns a list of possible string values of ConfigLogEncoding.
func ConfigLogEncodingNames() []string {
	tmp := make([]string, len(_ConfigLogEncodingNames))
	copy(tmp, _ConfigLogEncodingNames)
	return tmp
}

// ConfigLogEncodingValues returns a list of the values for ConfigLogEncoding
func ConfigLogEncodingValues() []ConfigLogEncoding {
	return []ConfigLogEncoding{
		ConfigLogEncodingJson,
		ConfigLogEncodingConsole,
	}
}

// String implements the Stringer interface.
func (x ConfigLogEncoding) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogEncoding) IsValid() bool {
	_, err := ParseConfigLogEncoding(string(x))
	return err == nil
}

var _ConfigLogEncodingValue = map[string]ConfigLogEncoding{
	"json":    ConfigLogEncodingJson,
	"console": ConfigLogEncodingConsole,
}

// ParseConfigLogEncoding attempts to convert a string to a ConfigLogEncoding.
func ParseConfigLogEncoding(name string) (ConfigLogEncoding, error) {
	if x, ok := _ConfigLogEncodingValue[name]; ok {
		return x, nil
	}
	return ConfigLogEncoding(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogEncoding)
}

// MustParseConfigLogEncoding converts a string to a ConfigLogEncoding, and panics if is not valid.
func MustParseConfigLogEncoding(name string) ConfigLogEncoding {
	val, err := ParseConfigLogEncoding(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogEncoding) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogEncoding) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogEncoding(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigLogEncoding) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigLogTimeEncoderEpoch is a ConfigLogTimeEncoder of type epoch.
	ConfigLogTimeEncoderEpoch ConfigLogTimeEncoder = "epoch"
	// ConfigLogTimeEncoderEpochmillis is a ConfigLogTimeEncoder of type epochmillis.
	ConfigLogTimeEncoderEpochmillis ConfigLogTimeEncoder = "epochmillis"
	// ConfigLogTimeEncoderEpochnanos is a ConfigLogTimeEncoder of type epochnanos.
	ConfigLogTimeEncoderEpochnanos ConfigLogTimeEncoder = "epochnanos"
	// ConfigLogTimeEncoderIso8601 is a ConfigLogTimeEncoder of type iso8601.
	ConfigLogTimeEncoderIso8601 ConfigLogTimeEncoder = "iso8601"
	// ConfigLogTimeEncoderRfc3339 is a ConfigLogTimeEncoder of type rfc3339.
	ConfigLogTimeEncoderRfc3339 ConfigLogTimeEncoder = "rfc3339"
	// ConfigLogTimeEncoderRfc3339nano is a ConfigLogTimeEncoder of type rfc3339nano.
	ConfigLogTimeEncoderRfc3339nano ConfigLogTimeEncoder = "rfc3339nano"
)

var ErrInvalidConfigLogTimeEncoder = fmt.Errorf("not a valid ConfigLogTimeEncoder, try [%s]", strings.Join(_ConfigLogTimeEncoderNames, ", "))

var _ConfigLogTimeEncoderNames = []string{
	string(ConfigLogTimeEncoderEpoch),
	string(ConfigLogTimeEncoderEpochmillis),
	string(ConfigLogTimeEncoderEpochnanos),
	string(ConfigLogTimeEncoderIso8601),
	string(ConfigLogTimeEncoderRfc3339),
	string(ConfigLogTimeEncoderRfc3339nano),
}

// ConfigLogTimeEncoderNames returns a list of possible string values of ConfigLogTimeEncoder.
func ConfigLogTimeEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogTimeEncoderNames))
	copy(tmp, _ConfigLogTimeEncoderNames)
	return tmp
}

// ConfigLogTimeEncoderValues returns a list of the values for ConfigLogTimeEncoder
func ConfigLogTimeEncoderValues() []ConfigLogTimeEncoder {
	return []ConfigLogTimeEncoder{
		ConfigLogTimeEncoderEpoch,
		ConfigLogTimeEncoderEpochmillis,
		ConfigLogTimeEncoderEpochnanos,
		ConfigLogTimeEncoderIso8601,
		ConfigLogTimeEncoderRfc3339,
		ConfigLogTimeEncoderRfc3339nano,
	}
}

// String implements the Stringer interface.
func (x ConfigLogTimeEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogTimeEncoder) IsValid() bool {
	_, err := ParseConfigLogTimeEncoder(string(x))
	return err == nil
}

var _ConfigLogTimeEncoderValue = map[string]ConfigLogTimeEncoder{
	"epoch":       ConfigLogTimeEncoderEpoch,
	"epochmillis": ConfigLogTimeEncoderEpochmillis,
	"epochnanos":  ConfigLogTimeEncoderEpochnanos,
	"iso8601":     ConfigLogTimeEncoderIso8601,
	"rfc3339":     ConfigLogTimeEncoderRfc3339,
	"rfc3339nano": ConfigLogTimeEncoderRfc3339nano,
}

// ParseConfigLogTimeEncoder attempts to convert a string to a ConfigLogTimeEncoder.
func ParseConfigLogTimeEncoder(name string) (ConfigLogTimeEncoder, error) {
	if x, ok := _ConfigLogTimeEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogTimeEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogTimeEncoder)
}

// MustParseConfigLogTimeEncoder converts a string to a ConfigLogTimeEncoder, and panics if is not valid.
func MustParseConfigLogTimeEncoder(name string) ConfigLogTimeEncoder {
	val, err := ParseConfigLogTimeEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogTimeEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogTimeEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogTimeEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigLogTimeEncoder) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
