// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package queue

import (
	"fmt"
	"strings"
)

const (
	// JobStatusPending is a JobStatus of type pending.
	JobStatusPending JobStatus = "pending"
	// JobStatusRunning is a JobStatus of type running.
	JobStatusRunning JobStatus = "running"
	// JobStatusDone is a JobStatus of type done.
	JobStatusDone JobStatus = "done"
	// JobStatusFailed is a JobStatus of type failed.
	JobStatusFailed JobStatus = "failed"
)

var ErrInvalidJobStatus = fmt.Errorf("not a valid JobStatus, try [%s]", strings.Join(_JobStatusNames, ", "))

var _JobStatusNames = []string{
	string(JobStatusPending),
	string(JobStatusRunning),
	string(JobStatusDone),
	string(JobStatusFailed),
}

// JobStatusNames returns a list of possible string values of JobStatus.
func JobStatusNames() []string {
	tmp := make([]string, len(_JobStatusNames))
	copy(tmp, _JobStatusNames)
	return tmp
}

// JobStatusValues returns a list of the values for JobStatus
func JobStatusValues() []JobStatus {
	return []JobStatus{
		JobStatusPending,
		JobStatusRunning,
		JobStatusDone,
		JobStatusFailed,
	}
}

// String implements the Stringer interface.
func (x JobStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x JobStatus) IsValid() bool {
	_, err := ParseJobStatus(string(x))
	return err == nil
}

var _JobStatusValue = map[string]JobStatus{
	"pending": JobStatusPending,
	"running": JobStatusRunning,
	"done":    JobStatusDone,
	"failed":  JobStatusFailed,
}

// ParseJobStatus attempts to convert a string to a JobStatus.
func ParseJobStatus(name string) (JobStatus, error) {
	if x, ok := _JobStatusValue[name]; ok {
		return x, nil
	}
	return JobStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidJobStatus)
}

// MustParseJobStatus converts a string to a JobStatus, and panics if is not valid.
func MustParseJobStatus(name string) JobStatus {
	val, err := ParseJobStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x JobStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *JobStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseJobStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *JobStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
