/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List jobs
		 * @description Returns a list of jobs, optionally filtered by status. Jobs are sorted by created_at descending (newest first).
		 */
		get: operations['listJobs'];
		put?: never;
		/**
		 * Enqueue a new job
		 * @description Creates a new job for the specified flow and adds it to the pending queue
		 */
		post: operations['enqueueJob'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/jobs/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a job by ID
		 * @description Returns the details of a specific job including its current status
		 */
		get: operations['getJob'];
		put?: never;
		post?: never;
		/**
		 * Delete a job
		 * @description Deletes a job from the queue regardless of its current status
		 */
		delete: operations['deleteJob'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/jobs/{id}/logs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get job logs
		 * @description Returns the execution logs for a completed job. Logs are only available after the job has finished (done or failed status).
		 */
		get: operations['getJobLogs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/flows': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all flows
		 * @description Returns a list of all flow names in the flows directory
		 */
		get: operations['listFlows'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/flows/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a flow by name
		 * @description Returns the content of a specific flow file
		 */
		get: operations['getFlow'];
		/**
		 * Add or update a flow
		 * @description Creates a new flow or updates an existing one with the provided content
		 */
		put: operations['addFlow'];
		post?: never;
		/**
		 * Delete a flow
		 * @description Removes a flow from the flows directory
		 */
		delete: operations['deleteFlow'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedules': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all schedules
		 * @description Returns a list of all configured schedules with their current state
		 */
		get: operations['listSchedules'];
		put?: never;
		/**
		 * Create a new schedule
		 * @description Creates a new schedule that will trigger jobs based on the specified type and expression
		 */
		post: operations['createSchedule'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedules/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a schedule by name
		 * @description Returns the details of a specific schedule including its next run time
		 */
		get: operations['getSchedule'];
		/**
		 * Update a schedule
		 * @description Updates an existing schedule with new configuration
		 */
		put: operations['updateSchedule'];
		post?: never;
		/**
		 * Delete a schedule
		 * @description Removes a schedule and stops any pending triggers
		 */
		delete: operations['deleteSchedule'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedules/{name}/enable': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Enable a schedule
		 * @description Enables a disabled schedule so it will trigger jobs again
		 */
		post: operations['enableSchedule'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/schedules/{name}/disable': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Disable a schedule
		 * @description Disables a schedule so it will no longer trigger jobs
		 */
		post: operations['disableSchedule'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * @description The current status of a job
		 * @enum {string}
		 */
		JobStatus: 'pending' | 'running' | 'done' | 'failed';
		/** @description A job in the queue */
		Job: {
			/**
			 * @description Unique job identifier (16 character hex string)
			 * @example a1b2c3d4e5f67890
			 */
			id: string;
			/**
			 * @description Name of the flow to execute
			 * @example my-workflow
			 */
			flow: string;
			/**
			 * @description Input key-value pairs passed to the flow
			 * @example {
			 *       "name": "test",
			 *       "environment": "production"
			 *     }
			 */
			inputs?: {
				[key: string]: string;
			};
			/**
			 * Format: date-time
			 * @description Timestamp when the job was created
			 * @example 2024-01-15T10:30:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @description Timestamp when the job started executing
			 * @example 2024-01-15T10:30:05Z
			 */
			started_at?: string | null;
			/**
			 * Format: date-time
			 * @description Timestamp when the job finished (successfully or with error)
			 * @example 2024-01-15T10:31:00Z
			 */
			ended_at?: string | null;
			/**
			 * @description Error message if the job failed
			 * @example step 'build' failed: exit code 1
			 */
			error?: string;
			/**
			 * @description Exit code of the job (0 for success, non-zero for failure)
			 * @example 0
			 */
			exit_code?: number | null;
		};
		JobWithStatus: components['schemas']['Job'] & {
			status: components['schemas']['JobStatus'];
		};
		/** @description Request to enqueue a new job */
		JobEnqueueRequest: {
			/**
			 * @description Name of the flow to execute (must exist in flows directory)
			 * @example my-workflow
			 */
			flow: string;
			/**
			 * @description Input key-value pairs to pass to the flow (available as YAFE_INPUT_* environment variables)
			 * @example {
			 *       "name": "test",
			 *       "environment": "production"
			 *     }
			 */
			inputs?: {
				[key: string]: string;
			};
		};
		/** @description Response after successfully enqueuing a job */
		JobEnqueueResponse: {
			/**
			 * @description The ID of the newly created job
			 * @example a1b2c3d4e5f67890
			 */
			job_id: string;
		};
		/** @description Error response */
		ErrorResponse: {
			/**
			 * @description Human-readable error message
			 * @example flow not found: unknown-flow
			 */
			error: string;
		};
		/** @description Flow details */
		FlowResponse: {
			/**
			 * @description Flow name
			 * @example my-workflow
			 */
			name: string;
			/**
			 * @description YAML content of the flow definition
			 * @example name: my-workflow
			 *     steps:
			 *       - name: hello
			 *         kind: shell
			 *         cmd: echo "Hello, World!"
			 */
			content: string;
		};
		/** @description Request to add or update a flow */
		AddFlowRequest: {
			/**
			 * @description YAML content of the flow definition
			 * @example name: my-workflow
			 *     steps:
			 *       - name: hello
			 *         kind: shell
			 *         cmd: echo "Hello, World!"
			 */
			content: string;
		};
		/**
		 * @description The type of schedule trigger
		 * @enum {string}
		 */
		ScheduleType: 'cron' | 'interval';
		/** @description Request to create a new schedule */
		CreateScheduleRequest: {
			/**
			 * @description Unique name for the schedule
			 * @example daily-backup
			 */
			name: string;
			/**
			 * @description Name of the flow to execute (must exist in flows directory)
			 * @example backup-flow
			 */
			flow: string;
			type: components['schemas']['ScheduleType'];
			/**
			 * @description Schedule expression (cron syntax for type "cron", duration like "5m" or "1h" for type "interval")
			 * @example 0 0 * * *
			 */
			expression: string;
			/**
			 * @description Input key-value pairs to pass to the flow
			 * @example {
			 *       "target": "database",
			 *       "retention": "7d"
			 *     }
			 */
			inputs?: {
				[key: string]: string;
			};
			/**
			 * @description Whether the schedule is enabled
			 * @default false
			 * @example true
			 */
			enabled: boolean;
		};
		/** @description Request to update an existing schedule */
		UpdateScheduleRequest: {
			/**
			 * @description Name of the flow to execute (must exist in flows directory)
			 * @example backup-flow
			 */
			flow: string;
			type: components['schemas']['ScheduleType'];
			/**
			 * @description Schedule expression (cron syntax for type "cron", duration like "5m" or "1h" for type "interval")
			 * @example 0 0 * * *
			 */
			expression: string;
			/**
			 * @description Input key-value pairs to pass to the flow
			 * @example {
			 *       "target": "database",
			 *       "retention": "7d"
			 *     }
			 */
			inputs?: {
				[key: string]: string;
			};
			/**
			 * @description Whether the schedule is enabled
			 * @example true
			 */
			enabled?: boolean;
		};
		/** @description Current user's profile */
		ProfileResponse: {
			/**
			 * @description Authenticated user's name. Empty string if authentication is not required.
			 * @example admin
			 */
			username: string;
			/**
			 * @description List of roles assigned to the user
			 * @example ["jobs:read", "jobs:write", "flows:read"]
			 */
			roles: string[];
		};
		/** @description Schedule details */
		ScheduleResponse: {
			/**
			 * @description Unique name for the schedule
			 * @example daily-backup
			 */
			name: string;
			/**
			 * @description Name of the flow to execute
			 * @example backup-flow
			 */
			flow: string;
			type: components['schemas']['ScheduleType'];
			/**
			 * @description Schedule expression
			 * @example 0 0 * * *
			 */
			expression: string;
			/**
			 * @description Input key-value pairs passed to the flow
			 * @example {
			 *       "target": "database",
			 *       "retention": "7d"
			 *     }
			 */
			inputs?: {
				[key: string]: string;
			};
			/**
			 * @description Whether the schedule is enabled
			 * @example true
			 */
			enabled: boolean;
			/**
			 * Format: date-time
			 * @description Timestamp when the schedule was created
			 * @example 2024-01-15T10:30:00Z
			 */
			created_at: string;
			/**
			 * Format: date-time
			 * @description Timestamp of the last triggered job
			 * @example 2024-01-16T00:00:00Z
			 */
			last_run_at?: string | null;
			/**
			 * Format: date-time
			 * @description Computed timestamp of the next scheduled trigger (null if disabled)
			 * @example 2024-01-17T00:00:00Z
			 */
			next_run_at?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	listJobs: {
		parameters: {
			query?: {
				/** @description Filter by job status. Can be specified multiple times to include multiple statuses. If not specified, all statuses are returned. */
				status?: components['schemas']['JobStatus'][];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of jobs */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Job'][];
				};
			};
			/** @description Invalid status parameter */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	enqueueJob: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobEnqueueRequest'];
			};
		};
		responses: {
			/** @description Job accepted and enqueued */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobEnqueueResponse'];
				};
			};
			/** @description Invalid request body or missing required fields */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Flow not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getJob: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Job ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Job details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobWithStatus'];
				};
			};
			/** @description Job ID is required */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Job not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteJob: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Job ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Job deleted successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Job ID is required */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Job not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getJobLogs: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Job ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Job logs */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			/** @description Job ID is required */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Job not found or logs not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Job logs not yet available (job is still pending or running) */
			425: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listFlows: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of flow names */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': string[];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getFlow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Flow name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Flow details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['FlowResponse'];
				};
			};
			/** @description Invalid flow name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Flow not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	addFlow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Flow name */
				name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AddFlowRequest'];
			};
		};
		responses: {
			/** @description Flow created or updated successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid flow name or missing content */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteFlow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Flow name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Flow deleted successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid flow name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Flow not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listSchedules: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of schedules */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleResponse'][];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateScheduleRequest'];
			};
		};
		responses: {
			/** @description Schedule created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request body or validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule already exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schedule name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Schedule details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScheduleResponse'];
				};
			};
			/** @description Invalid schedule name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	updateSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schedule name */
				name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateScheduleRequest'];
			};
		};
		responses: {
			/** @description Schedule updated successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid request body or validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schedule name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Schedule deleted successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid schedule name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	enableSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schedule name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Schedule enabled successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid schedule name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	disableSchedule: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Schedule name */
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Schedule disabled successfully */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid schedule name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Schedule not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Scheduler not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
}
