// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package scheduler

import (
	"fmt"
	"strings"
)

const (
	// ScheduleTypeCron is a ScheduleType of type cron.
	ScheduleTypeCron ScheduleType = "cron"
	// ScheduleTypeInterval is a ScheduleType of type interval.
	ScheduleTypeInterval ScheduleType = "interval"
)

var ErrInvalidScheduleType = fmt.Errorf("not a valid ScheduleType, try [%s]", strings.Join(_ScheduleTypeNames, ", "))

var _ScheduleTypeNames = []string{
	string(ScheduleTypeCron),
	string(ScheduleTypeInterval),
}

// ScheduleTypeNames returns a list of possible string values of ScheduleType.
func ScheduleTypeNames() []string {
	tmp := make([]string, len(_ScheduleTypeNames))
	copy(tmp, _ScheduleTypeNames)
	return tmp
}

// ScheduleTypeValues returns a list of the values for ScheduleType
func ScheduleTypeValues() []ScheduleType {
	return []ScheduleType{
		ScheduleTypeCron,
		ScheduleTypeInterval,
	}
}

// String implements the Stringer interface.
func (x ScheduleType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ScheduleType) IsValid() bool {
	_, err := ParseScheduleType(string(x))
	return err == nil
}

var _ScheduleTypeValue = map[string]ScheduleType{
	"cron":     ScheduleTypeCron,
	"interval": ScheduleTypeInterval,
}

// ParseScheduleType attempts to convert a string to a ScheduleType.
func ParseScheduleType(name string) (ScheduleType, error) {
	if x, ok := _ScheduleTypeValue[name]; ok {
		return x, nil
	}
	return ScheduleType(""), fmt.Errorf("%s is %w", name, ErrInvalidScheduleType)
}

// MustParseScheduleType converts a string to a ScheduleType, and panics if is not valid.
func MustParseScheduleType(name string) ScheduleType {
	val, err := ParseScheduleType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ScheduleType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ScheduleType) UnmarshalText(text []byte) error {
	tmp, err := ParseScheduleType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ScheduleType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
