// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package auth

import (
	"fmt"
	"strings"
)

const (
	// RoleJobsread is a Role of type jobs:read.
	RoleJobsread Role = "jobs:read"
	// RoleJobswrite is a Role of type jobs:write.
	RoleJobswrite Role = "jobs:write"
	// RoleFlowsread is a Role of type flows:read.
	RoleFlowsread Role = "flows:read"
	// RoleFlowswrite is a Role of type flows:write.
	RoleFlowswrite Role = "flows:write"
	// RoleSchedulesread is a Role of type schedules:read.
	RoleSchedulesread Role = "schedules:read"
	// RoleScheduleswrite is a Role of type schedules:write.
	RoleScheduleswrite Role = "schedules:write"
)

var ErrInvalidRole = fmt.Errorf("not a valid Role, try [%s]", strings.Join(_RoleNames, ", "))

var _RoleNames = []string{
	string(RoleJobsread),
	string(RoleJobswrite),
	string(RoleFlowsread),
	string(RoleFlowswrite),
	string(RoleSchedulesread),
	string(RoleScheduleswrite),
}

// RoleNames returns a list of possible string values of Role.
func RoleNames() []string {
	tmp := make([]string, len(_RoleNames))
	copy(tmp, _RoleNames)
	return tmp
}

// RoleValues returns a list of the values for Role
func RoleValues() []Role {
	return []Role{
		RoleJobsread,
		RoleJobswrite,
		RoleFlowsread,
		RoleFlowswrite,
		RoleSchedulesread,
		RoleScheduleswrite,
	}
}

// String implements the Stringer interface.
func (x Role) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Role) IsValid() bool {
	_, err := ParseRole(string(x))
	return err == nil
}

var _RoleValue = map[string]Role{
	"jobs:read":       RoleJobsread,
	"jobs:write":      RoleJobswrite,
	"flows:read":      RoleFlowsread,
	"flows:write":     RoleFlowswrite,
	"schedules:read":  RoleSchedulesread,
	"schedules:write": RoleScheduleswrite,
}

// ParseRole attempts to convert a string to a Role.
func ParseRole(name string) (Role, error) {
	if x, ok := _RoleValue[name]; ok {
		return x, nil
	}
	return Role(""), fmt.Errorf("%s is %w", name, ErrInvalidRole)
}

// MustParseRole converts a string to a Role, and panics if is not valid.
func MustParseRole(name string) Role {
	val, err := ParseRole(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x Role) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Role) UnmarshalText(text []byte) error {
	tmp, err := ParseRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Role) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
